bundle = "helpers"
iam_role_prefix = "pf-example-"
preprocessor = "zendesk_common.preprocessor.preprocess"
layers = ["arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:79"]
subnets=["subnet-707a1eeloaded", "subnet-d3adb33f" , "subnet-badcafe"]

[tags]
app = "picofun-zendesk"
env = "poc"