bundle = "helpers"
iam_role_prefix = "pf-zendesk-"
preprocessor = "zendesk_common.preprocessor.preprocess"
subnets=["subnet-707a1eeloaded", "subnet-d3adb33f", "subnet-badcafe"]
vpc_id = "vpc-0011223344556677f"

[tags]
app = "picofun-zendesk"
env = "poc"