bundle = "helpers"
preprocessor = "zendesk_common.preprocessor.preprocess"
layers = ["arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:79"]

[tags]
app = "picofun-zendesk"
env = "poc"