version: 2

updates:
  - package-ecosystem: uv
    directories:
      - "/"
      - "/examples/cdk"
      - "/examples/swagger-meraki"
      - "/examples/github-app-cdk"
      - "/examples/github-app-cdk/helpers"
      - "/examples/github-app-cdk/rotation"
    schedule:
      interval: daily
      time: "02:00"
    cooldown:
      default-days: 1
    groups:
      boto:
        patterns:
          - "boto*"
      cdk:
        patterns:
          - "aws-cdk-*"
          - "constructs*"
      powertools:
        patterns:
          - "aws-lambda-powertools*"
      pytest:
        patterns:
          - "coverage*"
          - "pytest*"
      qa:
        patterns:
          - "ruff*"
          - "ty*"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/examples/zendesk"
    schedule:
      interval: "daily"
      time: "03:00"
    cooldown:
      default-days: 1
    labels:
      - "dependencies"
      - "actions"
    open-pull-requests-limit: 5
