name: "Deploy"
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 6'

jobs:

  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Set up Python
        run: uv python install

      - name: Run PicoFun
        id: run-picofun
        run: uvx run picofun --config-file picofun.toml zendesk https://developer.zendesk.com/zendesk/oas.yaml

      - name: Copy Extra Terraform Files
        id: copy-extra-tf-files
        run: cp *.tf output/

      - name: Setup TFLint
        id: setup-tflint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2

      - name: Init TFLint
        id: init-tflint
        run: tflint --init
        env:
          # Needed to avoid getting rate limited by GitHub API
          GITHUB_TOKEN: ${{ github.token }}

      - name: TFLint
        id: tflint
        run: tflint
        working-directory: ./output

      - name: TFSec
        id: tfsec
        uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6 # v1.0.3
        with:
          # Avoiding rate limit again
          github_token: ${{ github.token }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        id: tf-setup
        with:
          terraform_version: 1.9.8

      - name: AWS Login
        id: aws-login
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: Terraform init
        id: tf-init
        run: terraform init
        working-directory: ./output

      - name: Terraform validate
        id: tf-validate
        run: terraform validate
        working-directory: ./output

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./output
