name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Ruff Check
        run: ruff check --output-format=github .

      - name: Ruff Format
        run: ruff format --check .
          
      - name: pytest
        run: |
          python -m pytest --capture=no tests/
