name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Dependencies
        run: uv sync --all-extras --dev

      - name: Ruff Check
        run: uv run ruff check --output-format=github .

      - name: Ruff Format
        run: uv run ruff format --check .
          
      - name: pytest
        run: uv run coverage run -m pytest

      - name: coverage
        run: uv run coverage report