name: CI

on: [push, pull_request]

permissions: {}

jobs:
  build:

    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Set up Python
        run: uv python install

      - name: Dependencies
        run: uv sync --all-extras --dev

      - name: Ruff Check
        run: uv run ruff check --output-format=github .

      - name: Ruff Format
        run: uv run ruff format --output-format=github --check .

      - name: Type Check
        run: uv run ty check --output-format=github .

      - name: pytest
        run: uv run coverage run -m pytest tests

      - name: coverage
        run: uv run coverage report

      - name: build
        run: uv build
